server:
  port: 18085
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          # 配置gitee的仓库地址
          uri: https://gitee.com/lilongcheng/config.git
  # rabbitmq的配置信息；如下配置的rabbit都是默认值，其实可以完全不配置
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
# 暴露触发消息总线的地址
management:
  endpoints:
    web:
      exposure:
        # 暴露触发消息总线的地址
        include: bus-refresh
eureka:
  client:
    service-url:
    # 注册Eureka Server集群
      defaultZone: http://127.0.0.1:7001/eureka
logging:
  level:
    com.itheima.application: debug
#    配置中心的作用:将各个微服务的配置文件集中到一起进行统一管理。
#    能搭建配置中心
#    需要在application.yml配置文件中指定需要远程更新的仓库地址。

#    修改微服务，从配置中心获取修改的配置