server:
  port: 6868
eureka:
  client:
    register-with-eureka: false #\u662F\u5426\u5C06\u81EA\u5DF1\u6CE8\u518C\u5230eureka\u4E2D
    fetch-registry: false #\u662F\u5426\u4ECEeureka\u4E2D\u83B7\u53D6\u4FE1\u606F
    service-url:
      defaultZone: http://127.0.0.1:${server.port}/eureka/