server:
  port: 7001
spring:
  application:
    name: euraka-server # 应用名称，会在Eureka中作为服务的id标识（serviceId）

eureka:
  client:
    register-with-eureka: false #是否将自己注册到Eureka中
    fetch-registry: false #是否从eureka中获取服务信息
    service-url:
      defaultZone: http://localhost:7001/euraka # EurekaServer的地址
#  server:
      # 关闭自我保护功能，默认是打开的
#      enable-self-preservation: false